# ---General---
# MiniMessage-formatted prefix (https://docs.advntr.dev/minimessage/format.html)
prefix: <dark_gray>[<green>Chat<white>-<dark_red>OG<dark_gray>]
blocklistEnabled: true
# Only blocklists with just a list of domains
blocklists:
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/multi.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/nsfw-onlydomains.txt

# ---Redis---
# Redis URL according to https://redis.github.io/lettuce/user-guide/connecting-redis/#uri-syntax
redisUrl: redis://$KEYDB_PASSWORD@127.0.0.1:6379/0

# TODO: Enable translation.
# ---OpenAI API Translation---
# Any OpenAI-compatible (OpenAI, ollama, llama.cpp) API will work here
openAIEnabled: false
# Will be used as: <baseurl>/v1/...
baseUrl: http://127.0.0.1:8080
apiKey: $OPENAI_API_KEY
# The name of the model. This isn't always required, for example with the llama-server "example" from llama.cpp
model: ""

# ---Discord---
# discordEnabled needs to be true for staffDiscordEnabled and premiumDiscordEnabled to have any effect
discordEnabled: true
staffDiscordEnabled: true
premiumDiscordEnabled: true
developerDiscordEnabled: true
status: Minecraft 1.19.4
serverHasStartedMessage: $BRAND_NAME 1.19.4 Beta 2 Server has started! <:stonks:899680228216029195>
serverHasStoppedMessage: $BRAND_NAME 1.19.4 Beta 2 Server has stopped! <:notstonks:939288625701617665>
botToken: $DISCORD_BOT_TOKEN
guildId: $DISCORD_GUILD_ID
channelId: $DISCORD_CHANNEL_ID
staffChannelId: $DISCORD_STAFF_ID
premiumChannelId: $DISCORD_PREMIUM_ID
developerChannelId: $DISCORD_DEVELOPER_ID
webhook: $DISCORD_MAIN_WEBHOOK
staffWebhook: $DISCORD_STAFF_WEBHOOK
premiumWebhook: $DISCORD_PREMIUM_WEBOOK
developerWebhook: $DISCORD_DEVELOPER_WEBHOOK
listCommandName: list
# Available placeholders: %onlineplayers%, %maxplayers%
listCommandText: "There are %onlineplayers% out of maximum 200 players online."

# TODO: Configure these roles.
useColorCodeRoles: false
# Configure which roles can use color codes with Discord -> Minecraft
# For example:
#
# colorCodeRoles: [1234567891274567890, 0987654321983654321]

# Configure the text color (after the username (Discord -> Minecraft)) for certain roles
# For example:
#
# roles:
#     1234567891239567890:
#         message_color: RED
#
# message_color can be one of the following: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
#
# You can also use RGB for the color:
#
# roles:
#     1234567891234567890:
#         message_color: [255, 255, 255]

# Configure the suffix for roles (has to include the space). color codes are allowed.
# For example:

# roleSuffixes:
#     1234567891234527890:
#         suffix: ": "
